trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: BuildPlatform
  value : 'x64'
- name: BuildConfiguration
  value: 'release'

resources:
  repositories:
    - repository: das-payments-v2-monitoring
      type: github
      name: SkillsFundingAgency/das-payments-v2-monitoring
      endpoint: SkillsFundingAgency

stages:
  
- stage: Code_Build
  displayName: 'Code Build'
  jobs:
  - template: pipeline-templates/job/code-build.yml
#- stage: Nuget_Push
  #displayName: 'Nuget Push'
  #jobs:
  #- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml