trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: BuildPlatform
  value : 'x64'
- name: BuildConfiguration
  value: 'release'

resources:
  repositories:
    - repository: das-payments-v2-monitoring
      type: github
      name: SkillsFundingAgency/das-payments-v2-monitoring
      endpoint: SkillsFundingAgency

stages:
  
- stage: Code Build
  displayName: 'Code Build'
  jobs:
  - template: pipeline-templates/job/code-build.yml
- stage: Nuget Push
  displayName: 'Nuget Push'
  jobs:
  dependsOn: Code Build
  - template: azure-pipelines-templates/deploy/stage/nuget-publish.yml

- stage: Deploy_DST
  displayName: 'Deploy to DST'
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-DST - Environment Key Vault Secrets

  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT
      environmentName: DST
      azureSubscription: DCT-VSO
      appName: DCOL-DST-MetricsFunc-WEU