trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: BuildPlatform
  value : 'x64'
- name: BuildConfiguration
  value: 'release'

resources:
  repositories:
    - repository: das-payments-v2-monitoring
      type: github
      name: SkillsFundingAgency/das-payments-v2-monitoring
      endpoint: SkillsFundingAgency

stages:
  
- stage: Code_Build
  displayName: 'Code Build'
  jobs:
  - template: pipeline-templates/job/code-build.yml
- stage: Nuget_Push
  displayName: 'Nuget Push'
  jobs:
  - template: azure-pipelines-templates/deploy/stage/nuget-publish.yml

- stage: Deploy_DST
  displayName: 'Deploy to DST'
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-DST - Environment Key Vault Secrets

  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT
      environmentName: DST
      azureSubscription: DCT-VSO
      appName: DCOL-DST-MetricsFunc-WEU

- stage: Deploy_DAS
  dependsOn: Deploy_DST
  displayName: Deploy to DAS
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-DAS - Environment Key Vault Secrets
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT
      environmentName: DAS
      azureSubscription: DCT-VSO
      appName: DCOL-DAS-MetricsFunc-WEU

- stage: Deploy_SIT
  dependsOn: Deploy_DAS
  displayName: Deploy to SIT
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-SIT - Environment Key Vault Secrets
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: SIT
      azureSubscription: DCT-VSO
      appName: DCOL-SIT-MonitoringAlerts1-WEU

- stage: Deploy_SDW
  dependsOn: Deploy_SIT
  displayName: Deploy to SDW
  variables:
  - name: tagEnvironment
    value: Dev/Test
  - group: DCOL-SDW - Environment Key Vault Secrets
  jobs:
  - template: pipeline-templates/deploy.yml
    parameters:
      pool: DCT Build Pool
      environmentName: SDW
      azureSubscription: DCOL-Shadow
      appName: DCOL-SDW-MonitoringAlerts1-WEU