using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NServiceBus;
using NUnit.Framework;
using Reqnroll;
using SFA.DAS.Payments.Monitoring.Jobs.Messages.Commands;
using SFA.DAS.Payments.Monitoring.Tests.Specs.Messages;

namespace SFA.DAS.Payments.Monitoring.Tests.Specs.StepDefinitions
{
    [Binding]
    public class MonitoringStepDefinitions
    {
        private static readonly Random Random = new Random();
        private readonly TestSession testSession;

        public MonitoringStepDefinitions(TestSession testSession)
        {
            this.testSession = testSession;
        }

        [Given(@"a payment transaction related to the DAS Funding platform is processed through the NServiceBus pipeline")]
        public void GivenADasFundingPaymentTransaction()
        {
            // Earnings coming from the DAS earnings calc are sent with JobId = 0.
            testSession.JobId = 0;
        }

        [Given(@"a message associated with an SLD-initiated job is processed through the NServiceBus pipeline")]
        public void GivenAnSldInitiatedJobMessage()
        {
            testSession.JobId = Random.Next(1, int.MaxValue);
        }

        [When(@"it passes through the Job Status Incoming Message, Job Status Outgoing Message, or Job Status Failed Message behaviours")]
        [When(@"it passes through the monitoring behaviours")]
        public async Task WhenItPassesThroughTheMonitoringBehaviours()
        {
            await SendAndWait(shouldFail: false);
            await SendAndWait(shouldFail: true);
        }

        [Then(@"the message is ignored by the monitoring behaviours")]
        public void ThenTheMessageIsIgnoredByTheMonitoringBehaviours()
        {
            Assert.That(ProcessedCallsForThisJob(), Is.Empty);
        }

        [Then(@"no attempt is made to determine an associated SLD job")]
        public void ThenNoAttemptIsMadeToDetermineAnAssociatedSldJob()
        {
            Assert.That(FailedCallsForThisJob(), Is.Empty);
        }

        [Then(@"no exceptions are generated by the required payments service")]
        public void ThenNoExceptionsAreGenerated()
        {
            Assert.That(testSession.UnhandledException, Is.Null);
        }

        [Then(@"the message continues to be monitored as it is today")]
        public void ThenTheMessageContinuesToBeMonitored()
        {
            var processedCalls = ProcessedCallsForThisJob().ToList();
            Assert.That(processedCalls.Count, Is.EqualTo(1));

            // Also proves JobStatusOutgoingMessageBehaviour recorded the event
            // published while handling - not just that Incoming behaviour fired.
            Assert.That(processedCalls.Single().GeneratedMessages.Count, Is.EqualTo(1));
        }

        [Then(@"an associated SLD job is determined where applicable")]
        public void ThenAnAssociatedSldJobIsDetermined()
        {
            Assert.That(FailedCallsForThisJob().Count(), Is.EqualTo(1));
        }

        private async Task SendAndWait(bool shouldFail)
        {
            try
            {
                await TestRunBindings.Endpoint.Send(
                    new TestMonitoredCommand { JobId = testSession.JobId, ShouldFail = shouldFail },
                    new SendOptions());
            }
            catch (Exception ex)
            {
                testSession.UnhandledException = ex;
            }

            await WaitUntil(
                () => shouldFail ? FailedCallsForThisJob().Any() : ProcessedCallsForThisJob().Any(),
                TimeSpan.FromSeconds(10));
        }

        private static async Task WaitUntil(Func<bool> condition, TimeSpan timeout)
        {
            var deadline = DateTime.UtcNow + timeout;
            while (DateTime.UtcNow < deadline && !condition())
            {
                await Task.Delay(TimeSpan.FromMilliseconds(100));
            }
        }

        private IEnumerable<RecordJobMessageProcessingStatus> ProcessedCallsForThisJob()
        {
            return TestRunBindings.JobStatusMessageSession.SentMessages
                .OfType<RecordJobMessageProcessingStatus>()
                .Where(m => m.JobId == testSession.JobId && m.Succeeded);
        }

        private IEnumerable<RecordJobMessageProcessingStatus> FailedCallsForThisJob()
        {
            return TestRunBindings.JobStatusMessageSession.SentMessages
                .OfType<RecordJobMessageProcessingStatus>()
                .Where(m => m.JobId == testSession.JobId && !m.Succeeded);
        }
    }
}
