Feature: PV2-4013 - DAS Funding platform earnings should not be monitored

Scenario: Monitoring service should not monitor the processing of DAS Funding platform earnings

Given a payment transaction related to the DAS Funding platform is processed through the NServiceBus pipeline
When it passes through the Job Status Incoming Message, Job Status Outgoing Message, or Job Status Failed Message behaviours
Then the message is ignored by the monitoring behaviours
And no attempt is made to determine an associated SLD job
And no exceptions are generated by the required payments service

Scenario: Monitoring behaviours continue to monitor the processing of SLD Funding platform earnings

Given a message associated with an SLD-initiated job is processed through the NServiceBus pipeline
When it passes through the monitoring behaviours
Then the message continues to be monitored as it is today
And an associated SLD job is determined where applicable
